### PR TITLE
API control of the media-scanner

### PR DESCRIPTION
**Pull request by jstarpl**
This PR introduces an API to control the media-scanner from the media-manager. The REST API generally follows the existing structure of methods. The state (remote controlled vs automatic scanning) is persisted locally by the media-scanner.

### CODE REVIEW

**Comment by baltedewit** [comment]
@jesperstarkar `manual-mode` or `manualmode`? It can't be case _insensitive_, but we can remove the uppercasing if you want? (Which would in turn also require changes to media-manager)

**Comment by jesperstarkar** [comment]
Being insensitive is just a matter of accepting both variants in the express endpoint?

I'd prefer lowercase as the default

**Comment by baltedewit** [comment]
Never mind, we should read the manual more often. Express end points are already case insensitive by default, case closed.

ps:
> Being insensitive is just a matter of accepting both variants in the express endpoint?

Routes aren't a giant if-else statement, so it's not a matter of accepting a variant. It's like having two addresses pointing to the same house. A lot more complicated than simply accepting something.

**Comment by jesperstarkar** [comment]
Back in the days we .htaccess-ed the shit out of these cases.

**Pull request merged**
